### ISSUE TITLE
install path is hardcoded in data/sdtest.sh

### ISSUE THREAD

**Issue by oluc** [raspberrypi-ui/agnostics#12]
install path is hardcoded in data/sdtest.sh, line 7:

`    RES=$(fio --output-format=terse --max-jobs=4 /usr/share/agnostics/sd_bench.fio | cut -f 3,7,8,48,49 -d";" -)`

if you install it somewhere else, like in /usr/local, then it fails finding sd_bench.fio (which then is in /usr/local/share/ not in /usr/share/)

**Comment by oluc** [comment]
there are more hardcoded paths, if you want to run `sdtest.sh` from the command line.

```
- sd_bench.fio,   line 11   : directory=/var/tmp
- sdtest.sh,      line 32   : rm -f /var/tmp/sd.test.file
```

I wish we could just run, alternatively
```
$ sdtest.sh                         ## to run on '/'
$ sdtest.sh /where/is/my/SD/card    ## to run on another card
```

**Comment by spl237** [comment]
If you are rebuilding yourself (which is the only reason it would be in /usr/local) then you can fix paths yourself as well. Not an issue for the vast majority of users.
