### ISSUE TITLE
Publish agnostics-cli package with fewer dependencies

### ISSUE THREAD

**Issue by hickford** [raspberrypi-ui/agnostics#13]
Hi. For those running a headless system, consider publishing an agnostics-cli package with just the command line interface and fewer dependencies (viz. libgtk etc)

> The following additional packages will be installed:
>  adwaita-icon-theme at-spi2-core dbus-user-session dconf-gsettings-backend dconf-service fio fontconfig glib-networking  glib-networking-common glib-networking-services gsettings-desktop-schemas gtk-update-icon-cache hicolor-icon-theme ibverbs-providers libaio1 libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0 libboost-atomic1.67.0 libboost-regex1.67.0 libboost-thread1.67.0  libcairo-gobject2 libcolord2 libcroco3 libdconf1 libepoxy0 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgfapi0  libgfrpc0 libgfxdr0 libglusterfs0 libgtk-3-0 libgtk-3-bin libgtk-3-common libgtksourceview-3.0-1 libgtksourceview-3.0-common libibverbs1   libjson-glib-1.0-0 libjson-glib-1.0-common libnuma1 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libproxy1v5 librados2 librbd1   librdmacm1 librest-0.7-0 librsvg2-2 librsvg2-common libsoup-gnome2.4-1 libsoup2.4-1 libwayland-client0 libwayland-cursor0   libwayland-egl1 libxkbcommon0 mousepad
> After this operation, 121 MB of additional disk space will be used.                                                

And a command /usr/bin/agnostics-cli that runs /usr/share/agnostics/sdtest.sh

**Comment by spl237** [comment]
Agnostics is a GUI package - we don't have the resource to support a separate CLI package. If people want to run a CLI version, it is easy enough to just download the relevant scripts from this repo (they're all in the data subdirectory) and run them from the CLI, but it's not something we support.
