### ISSUE TITLE
version 0.15 always reports FAIL

### ISSUE THREAD

**Issue by sgalke** [raspberrypi-ui/agnostics#20]
random write and random read IPOS are always reported as 0 - FAIL

**Comment by spl237** [comment]
Are you sure that isn't just an actual problem with your card? How do you know it is an issue with the application?

**Comment by sgalke** [comment]
yes, i am shure its v0.15. just before updating today, v014 reported IOPS > 0 - PASS, on pi5 $ KIOXA NVMe as well as on pi4 with SD  card. 

after update both report FAIL with IOPS   = 0 - FAIL.

**Comment by sgalke** [comment]
it i not the new binary v015 causng the error, agnostics v015 with an older configuration file is ok:

the bug sits somwhere in '/usr/share/agnostics/sd_bench.fio' 

i do not understand the contents of that file, but replacing this file  with the one from v14 (backup) seems to solve the problem ...

**Comment by sgalke** [comment]
deleted the 

[seq-read]
rw=read
bs=4m
stonewall

section in file  '/usr/share/agnostics/sd_bench.fio' seems tu solve the problem.

**Comment by kene101** [comment]
Just to add issue also started with new version here to

     Run 3
     prepare-file;0;0;34817;68
     seq-write;0;0;34000;8
     seq-read;44393;10;0;0
     rand-4k-write;0;0;3536;884
     rand-4k-read;6705;1676;0;0
     Sequential write speed 34000 KB/sec (target 10000) - PASS
     Random write speed 0 IOPS (target 500) - FAIL
     Random read speed 0 IOPS (target 1500) - FAIL

**Comment by spl237** [comment]
OK, problem found and fixed - new version uploading to apt now...

**Comment by sgalke** [comment]
thank you!

**Comment by kene101** [comment]
Run 1
     prepare-file;0;0;28646;55
     seq-write;0;0;36444;8
     seq-read;43351;10;0;0
     rand-4k-write;0;0;3285;821
     rand-4k-read;6934;1733;0;0
     Sequential write speed 36444 KB/sec (target 10000) - PASS
     Random write speed 821 IOPS (target 500) - PASS
     Random read speed 1733 IOPS (target 1500) - PASS
