### ISSUE TITLE
Run without UI

### ISSUE THREAD

**Issue by benjefferies** [raspberrypi-ui/agnostics#6]
I'm currently experiencing slowness with my pi zero and I wanted to test if it's related to a slow SD card. Came across this new tool and tried to run and realised it's on a UI application. It would be good to run just via the CLI.

```
pi@raspberrypi:~ $ agnostics
Unable to init server: Could not connect: Connection refused

(agnostics:3440): Gtk-WARNING **: 11:46:50.787: cannot open display:
```

**Comment by spl237** [comment]
Just run the test script itself - /bin/sh /usr/share/agnostics/sdtest.sh
