### ISSUE TITLE
fio: unable to open '/usr/share/agnostics/sd_bench.fio' job file

### ISSUE THREAD

**Issue by Sardonimous** [raspberrypi-ui/agnostics#9]
Following the build instructions in the README (without --prefix), the program builds correctly but when executed, sdtest.sh fails with "fio: unable to open '/usr/share/agnostics/sd_bench.fio' job file" because this file is stored in
/usr/local/share/agnostics.  Program erroneously considers this a PASS result.

rpdiags.txt:

Raspberry Pi Diagnostics - version (unknown)
Fri Jan  1 20:58:14 2021

Test : SD Card Speed Test
Run 1
fio: unable to open '/usr/share/agnostics/sd_bench.fio' job file

/usr/local/share/agnostics/sdtest.sh: 13: [: Illegal number: 
Sequential write speed  KB/sec (target 10000) - PASS
/usr/local/share/agnostics/sdtest.sh: 20: [: Illegal number: 
Random write speed  IOPS (target 500) - PASS
/usr/local/share/agnostics/sdtest.sh: 26: [: Illegal number: 
Random read speed  IOPS (target 1500) - PASS
Test PASS

**Comment by spl237** [comment]
> Following the build instructions in the README (without --prefix),...

You need to build *with* --prefix...
